KON-248 Refactor With Without Sequence Extensions
LemonAppDev/konsist pull request #287
Opened 2023-07-13 18:23 UTC by nataliapeterwas

2023-07-14 09:51 UTC, nataliapeterwas commented on lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoDeclaration.kt
>       */
I changed logic of the declaration package - but I still not sure if it makes sense. We will discuss it.

2023-07-14 09:55 UTC, nataliapeterwas commented
Pay attention to the KDocs - I'm not sure these descriptions are correct :D

2023-07-18 12:30 UTC, igorwojda requested changes

2023-07-18 12:30 UTC, igorwojda commented on lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/sequence/KoClassDeclarationSequenceExt.kt
> + * Sequence containing all classes that have any parent.
...have class or interface parent.

2023-07-18 12:30 UTC, igorwojda commented on lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/sequence/KoClassDeclarationSequenceExt.kt
> + * Sequence containing all classes that have any parent.
...have class or interface parent.

2023-07-18 12:30 UTC, igorwojda commented on lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/sequence/KoClassDeclarationSequenceExt.kt
> + * @return A sequence containing classes that have no parent.
..no parent - class does not extend any class and does not implement any interface.

2023-07-18 12:30 UTC, igorwojda commented on lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/sequence/KoClassDeclarationSequenceExt.kt
IN this method and all methods that have `name` or `names` arguments change "parent of type" to "names parents".

Same for "parent interface of type" -> "named parent interface"

2023-07-18 14:57 UTC, igorwojda approved these changes

2023-07-18 14:57 UTC, merged